---
title: "Asian Pop in LA"
author: "Katia Krotova"
date: "10/13/2021"
output: 
  html_document:
    code_folding: hide
---
```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

```

This map shows the percentage of Asian residents in each census block in Los Angeles County, California. This map is based on the data from the 2010 Decennial Census.

```{r, message = FALSE, warning = FALSE, echo=FALSE, include=FALSE}

library(leaflet)
library(sf)
library(tidyverse)
library(tidycensus)
library(ggthemes)
library(ggspatial)
library(htmlwidgets)
library(tidytransit)

```
 
```{r, message = FALSE, warning = FALSE, echo = FALSE, include=FALSE}

vars2010 <- load_variables(2010, "sf1")

```
 
```{r, message = FALSE, warning = FALSE, echo=FALSE, include=FALSE}

LA_Asian <- get_decennial(geography = "block",
                          state = "CA", county = "Los Angeles",
                          year = 2010,
                          output = "wide",
                          variables = c(tot_pop = 'P008001',
                                        as_pop = 'P008006'),
                          geometry = TRUE)

LA_Asian <- LA_Asian %>%
  mutate(pct_Asian = as_pop / tot_pop) %>%
  filter(tot_pop > 0)



```

```{r, message = FALSE, warning = FALSE}

LA_state_plane <- "+proj=aea +lat_1=34 +lat_2=40.5 +lat_0=0 +lon_0=-120 +x_0=0 +y_0=-4000000 +ellps=GRS80 +datum=NAD83 +units=m +no_defs"

```
 
 
```{r, message = FALSE, warning = FALSE}

LA_Asian_palette <- colorNumeric(c("cornsilk", "darkblue"), LA_Asian$pct_Asian)

Asian_map3 <- leaflet(LA_Asian) %>%
  addProviderTiles("Stamen.TonerLite") %>%
  addPolygons(color = ~LA_Asian_palette(pct_Asian), stroke = FALSE, fillOpacity = 0.7,
              highlightOptions = highlightOptions(fillColor = "darkorange", fillOpacity = 0.9),
              label = LA_Asian$NAME,
              popup = paste("Total population: ", LA_Asian$tot_pop, "<br/>",
                            "Asian population: ", LA_Asian$as_pop, " (", 
                            round(LA_Asian$pct_Asian * 100, 1), "%)", sep = "")) %>%
    addLegend("bottomright", pal = LA_Asian_palette, values = ~pct_Asian,
    title = "Percent of population<br/>identifying as Asian alone",
    labFormat = labelFormat(suffix = "%",
                            transform = function(x) 100 * x),
    opacity = 1)

Asian_map3

```
 
